### ISSUE TITLE
Does this require cloudflared running or some other tool?

### ISSUE THREAD

**Issue by josegonzalez** [zachfeldman/dokku-cf-tunnel-update#3]
My understanding is that some other tool needs to run to actually start the tunnel, but nothing like that is happening here. Am I missing a step in the readme?

**Comment by josegonzalez** [comment]
Also wanna say that this is pretty neat and I kinda want to find ways to make this work natively in Dokku!

**Comment by zachfeldman** [comment]
@josegonzalez good to hear from you sir! You may remember that I filed https://github.com/dokku/dokku/issues/6089 as well :)

Yes, it requires `cloudflared` - just updated the README to reflect this.

Glad you're enjoying it and happy to have you upstream any of this code!
